name: Push Assets

on:
  push:
    branches: [main]
    paths:
      - app/public/**

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push assets files
      uses: geraldoantonio/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'app/public/'
        destination_repo: 'geraldoantonio/lab-02'
        user_email: 'other@example'
        user_name: 'other'
        use_rsync: 'avhr'